name: flutter_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  hard_analyser: ^1.8.0

flutter:
  uses-material-design: true
